name: Run Script & Deploy HTML

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        id: run_script
        run: |
          chmod +x ./script.sh
          ./script.sh >script.log 2>&1 &
          echo $! >script.pid
          echo "Running (PID=$(cat script.pid))..."

      - name: Wait for completion
        run: |
          wait $(cat script.pid)
          echo "Script finished."

      - name: Check for HTML
        id: has_html
        run: |
          if [ -f output/report.html ]; then
            echo "::set-output name=present::true"
          else
            echo "::set-output name=present::false"
          fi

      # Upload the HTML as a Pages artifact
      - name: Upload Pages Artifact
        if: steps.has_html.outputs.present == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: steps.has_html.outputs.present == 'true'
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
